In [1]:
import pandas as pd

merged_df = pd.read_excel('../data/spreadsheets/merged_data.xlsx')

In [2]:
merged_df

,REGION,AVERAGE_AMOUNT_Credit,AVERAGE_AMOUNT_Debit,AVERAGE_AMOUNT_Financial,AVERAGE_AMOUNT_Incoming,AVERAGE_AMOUNT_Outgoing,AVERAGE_AMOUNT_Average
0,REGION III (CENTRAL LUZON),8470.925851,3460.568304,4631.935655,7783.420455,8470.925851,6563.555223
1,REGION XIII (CARAGA),8159.039619,3301.865253,5280.799588,6998.727055,8159.039619,6379.894227
2,REGION I (ILOCOS REGION),7971.156987,3288.860235,4250.786184,7397.099112,7971.156987,6175.811901
3,REGION II (CAGAYAN VALLEY),7935.049840,3240.817751,4499.650426,7665.621369,7935.049840,6255.237845
4,MIMAROPA REGION,7851.263737,3483.997271,5094.010641,7797.005408,7851.263737,6415.508159
5,REGION IX (ZAMBOANGA PENINSULA),7646.822475,3063.006817,4527.737955,6884.667505,7646.822475,5953.811445
6,REGION XI (DAVAO REGION),7517.073205,3098.707008,3830.645779,7663.441626,7517.073205,5925.388165
7,REGION VIII (EASTERN VISAYAS),7468.342945,3168.247962,4416.835740,7201.727165,7468.342945,5944.699351
8,REGION XII (SOCCSKSARGEN),7340.373327,2969.690233,4102.601668,6950.535603,7340.373327,5740.714831
9,REGION V (BICOL REGION),6951.928791,2974.650305,4490.354165,7234.741738,6951.928791,5720.720758
10,CORDILLERA ADMINISTRATIVE REGION (CAR),6643.129964,2892.406313,4003.594307,7155.667549,6643.129964,5467.585620
11,REGION X (NORTHERN MINDANAO),6444.246611,2880.510776,3911.120322,6807.374799,6444.246611,5297.499824
12,REGION VI (WESTERN VISAYAS),6145.602252,2942.184110,4128.789727,6480.262662,6145.602252,5168.488201
13,REGION VII (CENTRAL VISAYAS),5991.973229,2888.802347,4632.347594,6286.481118,5991.973229,5158.315503

In [6]:
selected_region = merged_df[merged_df['REGION'] == 'REGION I (ILOCOS REGION)']
selected_region['AVERAGE_AMOUNT_Credit'].sum()

7971.156986517688